List<String> loadImagesCache = [

  'transparent.png',

  //MAP
  'map/grass_1.png',
  'map/grass_2.png',
  'map/grass_3.png',
  'map/grass_4.png',
  'map/tree_1.png',
  'map/house_1.png',
  'map/building_2.png',
  'map/building_3.png',
  'map/building_4.png',
  'map/street_light_down.png',
  'map/street_light_left.png',
  'map/street_light_right.png',
  'map/street_light_up.png',

  'map/sidewalk_topRight.png',
  'map/sidewalk_topLeft.png',
  'map/sidewalk_topCenter.png',
  'map/sidewalk_centerRight.png',
  'map/sidewalk_centerLeft.png',
  'map/sidewalk_center.png',
  'map/sidewalk_bottomCenter.png',
  'map/sidewalk_bottomLeft.png',
  'map/sidewalk_bottomRight.png',

  'map/stop_sign.png',
  'map/cross_walk.png',
  'map/traffic_light.png',
  'map/road_line.png',


  "character/test.png",
  "character/shotgun.png",
  "character/pistol.png",
  "character/shell.png",
  "character/smoke.png",

  "blood/blood1.png",
  "blood/blood2.png",
  "blood/blood3.png",
  "blood/blood4.png",
  "blood/blood5.png",
  "blood/blood6.png",
  "blood/blood7.png",
  "blood/blood8.png",
  "blood/blood9.png",
  "blood/blood10.png",
  "blood/blood11.png",
  "blood/blood12.png",
  "blood/blood13.png",
  "blood/blood14.png",
  "blood/blood15.png",
  "blood/blood16.png",
  "blood/blood17.png",

  "character/torso_A_skin_1.png",

  "character/eyes_black.png",
  "character/eyebrows.png",


  "character/hand_right_small_gun_skin_1.png",
  "character/hand_right_big_gun_skin_1.png",
  "character/hand_left1_big_gun_skin_1.png",
  "character/hand_left2_big_gun_skin_1.png",


  "guns/nine_mm.png",
  "guns/shell.png",
  "guns/shotgun_shell.png",
  "guns/bullet_small.png",
  "guns/bullet_medium.png",
  "guns/bullet_large.png",
  "guns/face_flash.png",


  "guns/icon_small_bullet.png",
  "guns/icon_medium_bullet.png",
  "guns/icon_medium_heavy_bullet.png",
  "guns/icon_shotgun_bullet.png",
  "guns/icon_missle_bullet.png",


  "guns/ak47_baby_2.png",
  "guns/ak47_baby.png",
  "guns/ak47.png",
  "guns/ar_2.png",
  "guns/ar_heavy.png",
  "guns/ar_scope_heavy.png",
  "guns/ar_scope.png",
  "guns/baretta_mp38a_smg.png",
  "guns/bazooka.png",
  "guns/baretta_m9.png",
  "guns/carbine_2.png",
  "guns/carbine.png",
  "guns/glock_2.png",
  "guns/glock.png",
  "guns/glork_2.png",
  "guns/glork.png",
  "guns/hunting_rifle.png",
  "guns/m16.png",
  "guns/m249.png",
  "guns/magnum.png",
  "guns/revolver_snub.png",
  "guns/revolver.png",
  "guns/rpg.png",
  "guns/shotgun_dub.png",
  "guns/shotgun_pump.png",
  "guns/shotgun_saw_off.png",
  "guns/shotgun_tac_2.png",
  "guns/shotgun_tac_shells.png",
  "guns/shotgun_tac_short.png",
  "guns/shotgun_tac.png",
  "guns/smg8.png",
  "guns/sniper.png",
  "guns/tommy.png",
  "guns/uzi_2.png",
  "guns/uzi.png",

];